language: python

jobs:
  include:
    - name: "run test suite with python 3.6"
      python: 3.6
      env:
        - TOXENV=py36
    - name: "run test suite with python 3.7"
      python: 3.7
      env:
        - TOXENV=py37
    - name: "run test suite with python 3.8"
      python: 3.8
      env:
        - TOXENV=py38
    - name: "typing"
      python: 3.8
      env:
        - TOXENV=type

before_install:
  - pip install poetry
install:
  - pip install -U pip
  - pip install -U tox
  - tox --notest
script: tox
before_deploy:
  - poetry build
deploy:
  provider: script
  script: poetry publish --username=$PYPI_USER --password=$PYPI_PASS
  skip_existing: true
  on:
    tags: true
after_success:
  - coveralls
