language: python
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
before_install:
  - pip install poetry
install:
  - poetry install
script: pytest --cov=geojsplit
before_deploy:
  - poetry build
deploy:
  provider: script
  script: poetry publish --username $PYPI_USER --password $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
after_success:
  - coveralls
