language: python
matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
before_install:
  - pip install poetry
install:
  - poetry install
script: pytest --cov=geojsplit
before_deploy:
  - poetry config http-basic.pypi $PYPI_USER %PYPI_PASS
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
if: tag IS present
after_success:
  - coveralls
